services:
  frontend:
    container_name: shelter-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://backend.chermanx.ru/api}
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL:-https://backend.chermanx.ru/api}
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    restart: unless-stopped
